import {
  AdministrationSetupsRoute,
  ApprovalsSetupsRoute,
  DynamicSetupsRoute,
  OrganizationSetupsRoute,
  PersonalSetupsRoute,
  SettingsSetupsRoute,
  SecuritySetupsRoute,
  ImportsSetupsRoute,
} from './adminnistation-setups';
import {
  BranchesPermissions,
  CategoriesPermissions,
  CommitteesPermissions,
  EducationPermissions,
  DataSecurityRulesPermissions,
  GroupPermissions,
  HierarchyLevelsPermissions,
  HierarchyPermissions,
  LocationsPermissions,
  OfferClassificationPermissions,
  OrganizationGroupPermissions,
  PermissionsPermissions,
  PersonalClassificationPermissions,
  PositionClassificationPermissions,
  PositionsPermissions,
  PositionTitlePermissions,
  PreScreeningApprovalPermissions,
  ProjectsPermissions,
  SponsorsPermissions,
  UsersPermissions,
  WorkClassificationPermissions,
  WorkflowsPermissions,
  AgencyPermissions,
  EmployeesPermissions,
} from '../../permissions';

export const SetupsRoute = [
  {
    path: '/administration',
    name: 'Administration',
    // component: AdministrationSetup,
    layout: '/setups',
    default: true,
    authorize: false,
    isExact: false,
    isRecursive: true,
    defaultPermissions: {
      ...BranchesPermissions,
      ...PermissionsPermissions,
      ...CategoriesPermissions,
      ...DataSecurityRulesPermissions,
      ...GroupPermissions,
      ...UsersPermissions,
      ...EmployeesPermissions,
      ...AgencyPermissions,
    },
    isRoute: true,
    children: AdministrationSetupsRoute,
  },
  {
    path: '/organization',
    name: 'organization',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    defaultPermissions: {
      ...HierarchyPermissions,
      ...HierarchyLevelsPermissions,
      ...LocationsPermissions,
      ...OrganizationGroupPermissions,
      ...PositionTitlePermissions,
      ...PreScreeningApprovalPermissions,
      ...ProjectsPermissions,
      ...SponsorsPermissions,
      ...PositionsPermissions,
    },
    isRoute: true,
    children: OrganizationSetupsRoute,
  },
  {
    path: '/personal',
    name: 'personal',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    defaultPermissions: {
      ...EducationPermissions,
      ...OfferClassificationPermissions,
      ...PersonalClassificationPermissions,
      ...PositionClassificationPermissions,
      ...WorkClassificationPermissions,
    },
    isRoute: true,
    children: PersonalSetupsRoute,
  },
  {
    path: '/dynamic',
    name: 'dynamic',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    defaultPermissions: {
      //change later
      ...EducationPermissions,
      ...OfferClassificationPermissions,
      ...PersonalClassificationPermissions,
      ...PositionClassificationPermissions,
      ...WorkClassificationPermissions,
    },
    isRoute: true,
    children: DynamicSetupsRoute,
  },
  {
    path: '/approvals',
    name: 'personal',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    defaultPermissions: {
      ...CommitteesPermissions,
      ...WorkflowsPermissions,
    },
    isRoute: true,
    children: ApprovalsSetupsRoute,
  },
  {
    path: '/settings',
    name: 'settings',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    // defaultPermissions: {
    //   ...CommitteesPermissions,
    //   ...WorkflowsPermissions,
    // },
    isRoute: true,
    children: SettingsSetupsRoute,
  },
  {
    path: '/security',
    name: 'security',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    // defaultPermissions: {
    //   ...CommitteesPermissions,
    //   ...WorkflowsPermissions,
    // },
    isRoute: true,
    children: SecuritySetupsRoute,
  },
  {
    path: '/imports',
    name: 'imports',
    // component: AdministrationSetup,
    layout: '/setups',
    default: false,
    authorize: false,
    isExact: false,
    isRecursive: true,
    // defaultPermissions: {
    //   ...CommitteesPermissions,
    //   ...WorkflowsPermissions,
    // },
    isRoute: true,
    children: ImportsSetupsRoute,
  },
];
