version: '3.3'
services:
  web:
    container_name: recruiter-staging-Web
    build:
      context: ./
      dockerfile: docker/staging/nginx/Dockerfile
    ports:
      - 8012:80
      - 4433:443
    restart: always
    links:
      - node-recruiter
  node-recruiter:
    container_name: recruiter-staging-React
    build:
      context: ./
      dockerfile: docker/staging/Dockerfile
    ports:
      - 8000:8000
    restart: always
