export const CandidateTypes = {
  SUCCESS: 'CANDIDATE_SUCCESS',
  SUBMITTED: 'CANDIDATE_SUBMITTED',
  REJECTED: 'CANDIDATE_REJECTED',
  FAILED: 'CANDIDATE_FAILED',
  RESET: 'CANDIDATE_RESET',
  CLEAR: 'CANDIDATE_CLEAR',
};
