// Job list
export const GET_JOB_LIST_REQUEST = 'GET_JOB_LIST_REQUEST';
export const GET_JOB_LIST_SUCCESS = 'GET_JOB_LIST_SUCCESS';
export const GET_JOB_LIST_FAILED = 'GET_JOB_LIST_FAILED';

// Job Details
export const GET_JOB_DETAIL_REQUEST = 'GET_JOB_DETAIL_REQUEST';
export const GET_JOB_DETAIL_SUCCESS = 'GET_JOB_DETAIL_SUCCESS';
export const GET_JOB_DETAIL_FAILED = 'GET_JOB_DETAIL_FAILED';

// Job Pipeline
export const GET_JOB_PIPELINE_REQUEST = 'GET_JOB_PIPELINE_REQUEST';
export const GET_JOB_PIPELINE_SUCCESS = 'GET_JOB_PIPELINE_SUCCESS';
export const GET_JOB_PIPELINE_FAILED = 'GET_JOB_PIPELINE_FAILED';

// Candidate Modal
export const GET_CANDIDATE_DETAIL_REQUEST = 'GET_CANDIDATE_DETAIL_REQUEST';
export const GET_CANDIDATE_DETAIL_SUCCESS = 'GET_CANDIDATE_DETAIL_SUCCESS';
export const GET_CANDIDATE_DETAIL_FAILED = 'GET_CANDIDATE_DETAIL_FAILED';

// Reset
export const RESET_PIPELINE = 'RESET_PIPELINE';
