import {
  GetAllVisaNationalities,
  CreateVisaNationality,
  UpdateVisaNationality,
  GetVisaNationalityById,
  DeleteVisaNationalities,
  GetAllVisaGenders,
  CreateVisaGender,
  UpdateVisaGender,
  GetVisaGenderById,
  DeleteVisaGenders,
  GetAllVisaOccupations,
  CreateVisaOccupation,
  UpdateVisaOccupation,
  GetVisaOccupationById,
  DeleteVisaOccupations,
  GetAllVisaReligions,
  CreateVisaReligion,
  UpdateVisaReligion,
  GetVisaReligionById,
  DeleteVisaReligions,
  GetAllVisaIssuePlaces,
  CreateVisaIssuePlace,
  UpdateVisaIssuePlace,
  GetVisaIssuePlaceById,
  DeleteVisaIssuePlaces,
  StatusVisaNationality,
  StatusVisaGender,
  StatusVisaOccupation,
  StatusVisaReligion,
  StatusVisaIssuePlace,
  UpdateVisaBlockIssuePlace,
  CreateVisaBlockIssuePlace,
  GetVisaBlockIssuePlaceById,
  GetAllVisaBlockIssuePlaces,
  DeleteVisaBlockIssuePlaces,
  StatusVisaBlockIssuePlace,
  UpdateVisaSponsor,
  CreateVisaSponsor,
  GetVisaSponsorById,
  GetAllVisaSponsors,
  DeleteVisaSponsors,
  StatusVisaSponsor,
} from '../../../../services';
import VisaLookupsComponent from '../component/Visa-Lookups.Component';

export const VisaLookupsTabs = [
  {
    label: 'nationalities',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 1,
        label: 'nationalities',
        valueSingle: 'nationality',
        updateAPI: UpdateVisaNationality,
        createAPI: CreateVisaNationality,
        viewAPI: GetVisaNationalityById,
        listAPI: GetAllVisaNationalities,
        deleteAPI: DeleteVisaNationalities,
        statusAPI: StatusVisaNationality,
      },
    },
  },
  {
    label: 'genders',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 2,
        label: 'genders',
        valueSingle: 'gender',
        updateAPI: UpdateVisaGender,
        createAPI: CreateVisaGender,
        viewAPI: GetVisaGenderById,
        listAPI: GetAllVisaGenders,
        deleteAPI: DeleteVisaGenders,
        statusAPI: StatusVisaGender,
      },
    },
  },
  {
    label: 'occupations',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 3,
        label: 'occupations',
        valueSingle: 'occupation',
        updateAPI: UpdateVisaOccupation,
        createAPI: CreateVisaOccupation,
        viewAPI: GetVisaOccupationById,
        listAPI: GetAllVisaOccupations,
        deleteAPI: DeleteVisaOccupations,
        statusAPI: StatusVisaOccupation,
      },
    },
  },
  {
    label: 'religions',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 4,
        label: 'religions',
        valueSingle: 'religion',
        updateAPI: UpdateVisaReligion,
        createAPI: CreateVisaReligion,
        viewAPI: GetVisaReligionById,
        listAPI: GetAllVisaReligions,
        deleteAPI: DeleteVisaReligions,
        statusAPI: StatusVisaReligion,
      },
    },
  },
  {
    label: 'arriving-from',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 5,
        label: 'arriving-from',
        valueSingle: 'arriving-from',
        updateAPI: UpdateVisaIssuePlace,
        createAPI: CreateVisaIssuePlace,
        viewAPI: GetVisaIssuePlaceById,
        listAPI: GetAllVisaIssuePlaces,
        deleteAPI: DeleteVisaIssuePlaces,
        statusAPI: StatusVisaIssuePlace,
      },
    },
  },
  {
    label: 'block-issue-places',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 6,
        label: 'block-issue-places',
        valueSingle: 'block-issue-place',
        updateAPI: UpdateVisaBlockIssuePlace,
        createAPI: CreateVisaBlockIssuePlace,
        viewAPI: GetVisaBlockIssuePlaceById,
        listAPI: GetAllVisaBlockIssuePlaces,
        deleteAPI: DeleteVisaBlockIssuePlaces,
        statusAPI: StatusVisaBlockIssuePlace,
      },
    },
  },
  {
    label: 'sponsors',
    component: VisaLookupsComponent,
    props: {
      lookup: {
        key: 7,
        label: 'sponsors',
        valueSingle: 'sponsor',
        updateAPI: UpdateVisaSponsor,
        createAPI: CreateVisaSponsor,
        viewAPI: GetVisaSponsorById,
        listAPI: GetAllVisaSponsors,
        deleteAPI: DeleteVisaSponsors,
        statusAPI: StatusVisaSponsor,
      },
    },
  },
];
