import {
  CreateSetupsMajors,
  DeleteSetupsMajor,
  GetAllSetupsMajors,
  getSetupsMajorsById,
  UpdateSetupsMajors,
  CreateSetupsUniversities,
  DeleteSetupsUniversity,
  GetAllSetupsUniversities,
  getSetupsUniversitiesById,
  UpdateSetupsUniversities,
  CreateSetupsCourses,
  DeleteSetupsCourse,
  GetAllSetupsCourses,
  getSetupsCoursesById,
  UpdateSetupsCourses,
  CreateSetupsColleges,
  DeleteSetupsCollege,
  GetAllSetupsColleges,
  getSetupsCollegesById,
  UpdateSetupsColleges,
  CreateSetupsCertificates,
  DeleteSetupsCertificate,
  GetAllSetupsCertificates,
  getSetupsCertificatesById,
  UpdateSetupsCertificates,
  CreateSetupsSkills,
  DeleteSetupsSkill,
  GetAllSetupsSkills,
  GetSetupsSkillById,
  UpdateSetupsSkills,
  CreateSetupsCompetencies,
  DeleteSetupsCompetency,
  GetAllSetupsCompetencies,
  getSetupsCompetenciesById,
  UpdateSetupsCompetencies,
  UpdateSetupsDegreeTypes,
  CreateSetupsDegreeTypes,
  GetSetupsDegreeTypesById,
  GetAllSetupsDegreeTypes,
  DeleteSetupsDegreeType,
} from '../../../../services';
import { LookupsImportEnum, TablesNameEnum } from '../../../../enums';
import LookupsComponent from '../components/lookups/Lookups.Component';

export const EducationClassificationsTabs = [
  {
    label: 'universities',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 1,
        label: 'universities',
        valueSingle: 'university',
        feature_name: TablesNameEnum.AcademicUniversities.key,
        updateAPI: UpdateSetupsUniversities,
        createAPI: CreateSetupsUniversities,
        viewAPI: getSetupsUniversitiesById,
        listAPI: GetAllSetupsUniversities,
        deleteAPI: DeleteSetupsUniversity,
        importEnumItem: LookupsImportEnum.academic_university,
      },
    },
  },
  {
    label: 'colleges',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 2,
        label: 'colleges',
        valueSingle: 'college',
        feature_name: TablesNameEnum.AcademicCollages.key,
        parentKey: 'academic_university_uuid',
        parentAPI: GetAllSetupsUniversities,
        parentByIdAPI: getSetupsUniversitiesById,
        parentTitle: 'university',
        titleKey: 'name',
        updateAPI: UpdateSetupsColleges,
        createAPI: CreateSetupsColleges,
        viewAPI: getSetupsCollegesById,
        listAPI: GetAllSetupsColleges,
        deleteAPI: DeleteSetupsCollege,
        importEnumItem: LookupsImportEnum.college,
      },
    },
  },
  {
    label: 'majors',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 3,
        label: 'majors',
        valueSingle: 'major',
        feature_name: TablesNameEnum.AcademicMajors.key,
        updateAPI: UpdateSetupsMajors,
        createAPI: CreateSetupsMajors,
        viewAPI: getSetupsMajorsById,
        listAPI: GetAllSetupsMajors,
        deleteAPI: DeleteSetupsMajor,
        importEnumItem: LookupsImportEnum.academic_major,
      },
    },
  },
  {
    label: 'certificates',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 4,
        label: 'certificates',
        valueSingle: 'certificate',
        feature_name: TablesNameEnum.AcademicCertificates.key,
        updateAPI: UpdateSetupsCertificates,
        createAPI: CreateSetupsCertificates,
        viewAPI: getSetupsCertificatesById,
        listAPI: GetAllSetupsCertificates,
        deleteAPI: DeleteSetupsCertificate,
        importEnumItem: LookupsImportEnum.academic_certificate,
      },
    },
  },
  {
    label: 'courses',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 5,
        label: 'courses',
        valueSingle: 'course',
        feature_name: TablesNameEnum.AcademicCourses.key,
        updateAPI: UpdateSetupsCourses,
        createAPI: CreateSetupsCourses,
        viewAPI: getSetupsCoursesById,
        listAPI: GetAllSetupsCourses,
        deleteAPI: DeleteSetupsCourse,
        importEnumItem: LookupsImportEnum.academic_course,
      },
    },
  },
  {
    label: 'skills',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 7,
        label: 'skills',
        valueSingle: 'skill',
        feature_name: TablesNameEnum.AcademicSkills.key,
        updateAPI: UpdateSetupsSkills,
        createAPI: CreateSetupsSkills,
        viewAPI: GetSetupsSkillById,
        listAPI: GetAllSetupsSkills,
        deleteAPI: DeleteSetupsSkill,
        importEnumItem: LookupsImportEnum.academic_skill,
      },
    },
  },
  {
    label: 'competencies',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 8,
        label: 'competencies',
        valueSingle: 'competency',
        feature_name: TablesNameEnum.AcademicCompetencies.key,
        updateAPI: UpdateSetupsCompetencies,
        createAPI: CreateSetupsCompetencies,
        viewAPI: getSetupsCompetenciesById,
        listAPI: GetAllSetupsCompetencies,
        deleteAPI: DeleteSetupsCompetency,
        importEnumItem: LookupsImportEnum.academic_competency,
      },
    },
  },
  {
    label: 'degree-types',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 9,
        label: 'degree-types',
        valueSingle: 'degree-type',
        feature_name: TablesNameEnum.DegreeTypes.key,
        updateAPI: UpdateSetupsDegreeTypes,
        createAPI: CreateSetupsDegreeTypes,
        viewAPI: GetSetupsDegreeTypesById,
        listAPI: GetAllSetupsDegreeTypes,
        deleteAPI: DeleteSetupsDegreeType,
        importEnumItem: LookupsImportEnum.degree_type,
      },
    },
  },
];
