import {
  CreateEmployeeCompetency,
  DeleteEmployeeCompetency,
  GetAllEmployeeCompetency,
  GetEmployeeCompetencyById,
  UpdateEmployeeCompetency,
  CreateEmployeeAddress,
  DeleteEmployeeAddress,
  GetAllEmployeeAddress,
  GetEmployeeAddressById,
  UpdateEmployeeAddress,
  CreateEmployeeEducation,
  DeleteEmployeeEducation,
  GetAllEmployeeEducation,
  GetEmployeeEducationById,
  UpdateEmployeeEducation,
  CreateEmployeeCertificate,
  DeleteEmployeeCertificate,
  GetAllEmployeeCertificate,
  GetEmployeeCertificateById,
  UpdateEmployeeCertificate,
  CreateEmployeeDocument,
  DeleteEmployeeDocument,
  GetAllEmployeeDocument,
  GetEmployeeDocumentById,
  UpdateEmployeeDocument,
  CreateEmployeeAsset,
  DeleteEmployeeAsset,
  GetAllEmployeeAsset,
  GetEmployeeAssetById,
  UpdateEmployeeAsset,
  CreateEmployeeContract,
  DeleteEmployeeContract,
  GetAllEmployeeContract,
  GetEmployeeContractById,
  UpdateEmployeeContract,
  CreateEmployeeMedicalProfile,
  DeleteEmployeeMedicalProfile,
  GetAllEmployeeMedicalProfile,
  GetEmployeeMedicalProfileById,
  UpdateEmployeeMedicalProfile,
  CreateEmployeeCourse,
  DeleteEmployeeCourse,
  GetAllEmployeeCourse,
  GetEmployeeCourseById,
  UpdateEmployeeCourse,
  CreateEmployeeExperienceJob,
  DeleteEmployeeExperienceJob,
  GetAllEmployeeExperienceJob,
  GetEmployeeExperienceJobById,
  UpdateEmployeeExperienceJob,
  CreateEmployeeExperienceReference,
  DeleteEmployeeExperienceReference,
  GetAllEmployeeExperienceReference,
  GetEmployeeExperienceReferenceById,
  UpdateEmployeeExperienceReference,
  CreateEmployeeRelative,
  DeleteEmployeeRelative,
  GetAllEmployeeRelative,
  GetEmployeeRelativeById,
  UpdateEmployeeRelative,
  CreateEmployeeSpouse,
  DeleteEmployeeSpouse,
  GetAllEmployeeSpouse,
  GetEmployeeSpouseById,
  UpdateEmployeeSpouse,
  CreateEmployeeSon,
  DeleteEmployeeSon,
  GetAllEmployeeSon,
  GetEmployeeSonById,
  UpdateEmployeeSon,
  CreateEmployeeDaughter,
  DeleteEmployeeDaughter,
  GetAllEmployeeDaughter,
  GetEmployeeDaughterById,
  UpdateEmployeeDaughter,
} from '../../../../services';
import {
  CompetencyForm,
  AddressForm,
  EducationForm,
  CertificateForm,
  DocumentForm,
  AssetForm,
  ContractForm,
  MedicalProfileForm,
  CourseForm,
  ExperienceJobForm,
  ExperienceReferenceForm,
  RelativeForm,
  SpouseForm,
  SonForm,
  DaughterForm,
} from '../../administration-setups/users/tabs/employees/dialogs/empolyee-profile/sections';

import { TablesNameEnum } from '../../../../enums'; // change ?

import { GlobalSecondaryDateFormat } from '../../../../helpers/Middleware.Helper';
import LookupsComponent from '../components/lookups/Lookups.Component';

export const EmployeeProfileTabs = [
  {
    label: 'competencies',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 1,
        label: 'competencies',
        valueSingle: 'competency',
        feature_name: TablesNameEnum.Competencies.key,
        updateAPI: UpdateEmployeeCompetency,
        createAPI: CreateEmployeeCompetency,
        viewAPI: GetEmployeeCompetencyById,
        listAPI: GetAllEmployeeCompetency,
        deleteAPI: DeleteEmployeeCompetency,
        // datesFormats: [
        //   { key: 'created_at', value: GlobalSecondaryDateFormat },
        //   { key: 'updated_at', value: GlobalSecondaryDateFormat },
        // ],
      },
      dynamicComponent: true,
      Section: CompetencyForm,
    },
  },
  {
    label: 'addresses',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 2,
        label: 'addresses',
        valueSingle: 'address',
        feature_name: TablesNameEnum.Addresses.key,
        updateAPI: UpdateEmployeeAddress,
        createAPI: CreateEmployeeAddress,
        viewAPI: GetEmployeeAddressById,
        listAPI: GetAllEmployeeAddress,
        deleteAPI: DeleteEmployeeAddress,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: AddressForm,
    },
  },
  {
    label: 'educations',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 3,
        label: 'educations',
        valueSingle: 'education',
        feature_name: TablesNameEnum.Educations.key,
        updateAPI: UpdateEmployeeEducation,
        createAPI: CreateEmployeeEducation,
        viewAPI: GetEmployeeEducationById,
        listAPI: GetAllEmployeeEducation,
        deleteAPI: DeleteEmployeeEducation,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: EducationForm,
    },
  },
  {
    label: 'certificates',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 4,
        label: 'certificates',
        valueSingle: 'certificate',
        feature_name: TablesNameEnum.Certificates.key,
        updateAPI: UpdateEmployeeCertificate,
        createAPI: CreateEmployeeCertificate,
        viewAPI: GetEmployeeCertificateById,
        listAPI: GetAllEmployeeCertificate,
        deleteAPI: DeleteEmployeeCertificate,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'issue_date', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: CertificateForm,
    },
  },
  {
    label: 'documents',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 5,
        label: 'documents',
        valueSingle: 'document',
        feature_name: TablesNameEnum.Documents.key,
        updateAPI: UpdateEmployeeDocument,
        createAPI: CreateEmployeeDocument,
        viewAPI: GetEmployeeDocumentById,
        listAPI: GetAllEmployeeDocument,
        deleteAPI: DeleteEmployeeDocument,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: DocumentForm,
    },
  },
  {
    label: 'assets',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 6,
        label: 'assets',
        valueSingle: 'asset',
        feature_name: TablesNameEnum.Assets.key,
        updateAPI: UpdateEmployeeAsset,
        createAPI: CreateEmployeeAsset,
        viewAPI: GetEmployeeAssetById,
        listAPI: GetAllEmployeeAsset,
        deleteAPI: DeleteEmployeeAsset,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: AssetForm,
    },
  },
  {
    label: 'contracts',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 7,
        label: 'contracts',
        valueSingle: 'contract',
        feature_name: TablesNameEnum.Contracts.key,
        updateAPI: UpdateEmployeeContract,
        createAPI: CreateEmployeeContract,
        viewAPI: GetEmployeeContractById,
        listAPI: GetAllEmployeeContract,
        deleteAPI: DeleteEmployeeContract,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: ContractForm,
    },
  },
  {
    label: 'medical-profiles',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 8,
        label: 'medical-profiles',
        valueSingle: 'medical-profile',
        feature_name: TablesNameEnum.MedicalProfiles.key,
        updateAPI: UpdateEmployeeMedicalProfile,
        createAPI: CreateEmployeeMedicalProfile,
        viewAPI: GetEmployeeMedicalProfileById,
        listAPI: GetAllEmployeeMedicalProfile,
        deleteAPI: DeleteEmployeeMedicalProfile,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: MedicalProfileForm,
    },
  },
  {
    label: 'courses',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 9,
        label: 'courses',
        valueSingle: 'course',
        feature_name: TablesNameEnum.Courses.key,
        updateAPI: UpdateEmployeeCourse,
        createAPI: CreateEmployeeCourse,
        viewAPI: GetEmployeeCourseById,
        listAPI: GetAllEmployeeCourse,
        deleteAPI: DeleteEmployeeCourse,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: CourseForm,
    },
  },
  {
    label: 'experience-jobs',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 10,
        label: 'experience-jobs',
        valueSingle: 'experience-job',
        feature_name: TablesNameEnum.ExperienceJobs.key,
        updateAPI: UpdateEmployeeExperienceJob,
        createAPI: CreateEmployeeExperienceJob,
        viewAPI: GetEmployeeExperienceJobById,
        listAPI: GetAllEmployeeExperienceJob,
        deleteAPI: DeleteEmployeeExperienceJob,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'from_date', value: GlobalSecondaryDateFormat },
          { key: 'to_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: ExperienceJobForm,
    },
  },
  {
    label: 'experience-references',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 11,
        label: 'experience-references',
        valueSingle: 'experience-reference',
        feature_name: TablesNameEnum.ExperienceReferences.key,
        updateAPI: UpdateEmployeeExperienceReference,
        createAPI: CreateEmployeeExperienceReference,
        viewAPI: GetEmployeeExperienceReferenceById,
        listAPI: GetAllEmployeeExperienceReference,
        deleteAPI: DeleteEmployeeExperienceReference,
        // datesFormats: [
        //   { key: 'created_at', value: GlobalSecondaryDateFormat },
        //   { key: 'updated_at', value: GlobalSecondaryDateFormat },
        // ],
      },
      dynamicComponent: true,
      Section: ExperienceReferenceForm,
    },
  },
  {
    label: 'relatives',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 12,
        label: 'relatives',
        valueSingle: 'relative',
        feature_name: TablesNameEnum.Relatives.key,
        updateAPI: UpdateEmployeeRelative,
        createAPI: CreateEmployeeRelative,
        viewAPI: GetEmployeeRelativeById,
        listAPI: GetAllEmployeeRelative,
        deleteAPI: DeleteEmployeeRelative,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'birth_date', value: GlobalSecondaryDateFormat },
          { key: 'marriage_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: RelativeForm,
    },
  },
  {
    label: 'spouses',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 13,
        label: 'spouses',
        valueSingle: 'spouse',
        feature_name: TablesNameEnum.spouses.key,
        updateAPI: UpdateEmployeeSpouse,
        createAPI: CreateEmployeeSpouse,
        viewAPI: GetEmployeeSpouseById,
        listAPI: GetAllEmployeeSpouse,
        deleteAPI: DeleteEmployeeSpouse,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'birth_date', value: GlobalSecondaryDateFormat },
          { key: 'marriage_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: SpouseForm,
    },
  },
  {
    label: 'sons',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 14,
        label: 'sons',
        valueSingle: 'son',
        feature_name: TablesNameEnum.Sons.key,
        updateAPI: UpdateEmployeeSon,
        createAPI: CreateEmployeeSon,
        viewAPI: GetEmployeeSonById,
        listAPI: GetAllEmployeeSon,
        deleteAPI: DeleteEmployeeSon,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'birth_date', value: GlobalSecondaryDateFormat },
          { key: 'marriage_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: SonForm,
    },
  },
  {
    label: 'daughters',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 15,
        label: 'daughters',
        valueSingle: 'daughter',
        feature_name: TablesNameEnum.Daughters.key,
        updateAPI: UpdateEmployeeDaughter,
        createAPI: CreateEmployeeDaughter,
        viewAPI: GetEmployeeDaughterById,
        listAPI: GetAllEmployeeDaughter,
        deleteAPI: DeleteEmployeeDaughter,
        datesFormats: [
          // { key: 'created_at', value: GlobalSecondaryDateFormat },
          // { key: 'updated_at', value: GlobalSecondaryDateFormat },
          { key: 'birth_date', value: GlobalSecondaryDateFormat },
          { key: 'marriage_date', value: GlobalSecondaryDateFormat },
        ],
      },
      dynamicComponent: true,
      Section: DaughterForm,
    },
  },
];
