import {
  CreateSetupsCPRCourseTypes,
  CreateSetupsMOHLicenses,
  CreateSetupsQualificationTypes,
  CreateSetupsSaCouncils,
  CreateSetupsSaCouncilsCategory,
  DeleteSetupsCPRCourseType,
  DeleteSetupsMOHLicense,
  DeleteSetupsQualificationType,
  DeleteSetupsSaCouncil,
  DeleteSetupsSaCouncilCategory,
  GetAllSetupsCPRCourseTypes,
  GetAllSetupsMOHLicenses,
  GetAllSetupsQualificationTypes,
  GetAllSetupsSaCouncils,
  GetAllSetupsSaCouncilsCategory,
  getSetupsCPRCourseTypeById,
  getSetupsMOHLicenseById,
  getSetupsQualificationTypesById,
  getSetupsSaCouncilById,
  getSetupsSaCouncilCategoryById,
  UpdateSetupsCPRCourseType,
  UpdateSetupsMOHLicenses,
  UpdateSetupsQualificationTypes,
  UpdateSetupsSaCouncils,
  UpdateSetupsSaCouncilsCategory,
  // CreateSetupsBanks,
  // DeleteSetupsBank,
  // GetAllSetupsBanks,
  // getSetupsBankById,
  // UpdateSetupsBank,
} from '../../../../services';
import { LookupsImportEnum, TablesNameEnum } from '../../../../enums';

import LookupsComponent from '../components/lookups/Lookups.Component';
import { FileClassificationPermissions } from '../../../../permissions';

export const FileClassificationsTabs = [
  {
    label: 'qualification-types',
    component: LookupsComponent,
    defaultPermissions: FileClassificationPermissions.QualificationTypesPermissions,
    props: {
      lookup: {
        key: 1,
        label: 'qualification-types',
        valueSingle: 'qualification-type',
        feature_name: TablesNameEnum.QualificationTypes.key,
        updateAPI: UpdateSetupsQualificationTypes,
        createAPI: CreateSetupsQualificationTypes,
        viewAPI: getSetupsQualificationTypesById,
        listAPI: GetAllSetupsQualificationTypes,
        deleteAPI: DeleteSetupsQualificationType,
        importEnumItem: LookupsImportEnum.qualification_type,
      },
    },
  },
  {
    label: 'sa-councils',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 2,
        label: 'sa-councils',
        valueSingle: 'sa-council',
        feature_name: TablesNameEnum.SaCouncils.key,
        updateAPI: UpdateSetupsSaCouncils,
        createAPI: CreateSetupsSaCouncils,
        viewAPI: getSetupsSaCouncilById,
        listAPI: GetAllSetupsSaCouncils,
        deleteAPI: DeleteSetupsSaCouncil,
        importEnumItem: LookupsImportEnum.sa_councils,
      },
    },
  },
  {
    label: 'moh-licenses',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 3,
        label: 'moh-licenses',
        valueSingle: 'moh-license',
        feature_name: TablesNameEnum.MOHLicense.key,
        updateAPI: UpdateSetupsMOHLicenses,
        createAPI: CreateSetupsMOHLicenses,
        viewAPI: getSetupsMOHLicenseById,
        listAPI: GetAllSetupsMOHLicenses,
        deleteAPI: DeleteSetupsMOHLicense,
        importEnumItem: LookupsImportEnum.moh_license,
      },
    },
  },
  {
    label: 'cpr-course-types',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 4,
        label: 'cpr-course-types',
        valueSingle: 'cpr-course-type',
        feature_name: TablesNameEnum.CPRCourseTypes.key,
        updateAPI: UpdateSetupsCPRCourseType,
        createAPI: CreateSetupsCPRCourseTypes,
        viewAPI: getSetupsCPRCourseTypeById,
        listAPI: GetAllSetupsCPRCourseTypes,
        deleteAPI: DeleteSetupsCPRCourseType,
        importEnumItem: LookupsImportEnum.cpr_course_type,
      },
    },
  },
  {
    label: 'sa-councils-category',
    component: LookupsComponent,
    props: {
      lookup: {
        key: 5,
        label: 'sa-councils-categories',
        valueSingle: 'sa-councils-category',
        feature_name: TablesNameEnum.SaCouncilsCategory.key,
        updateAPI: UpdateSetupsSaCouncilsCategory,
        createAPI: CreateSetupsSaCouncilsCategory,
        viewAPI: getSetupsSaCouncilCategoryById,
        listAPI: GetAllSetupsSaCouncilsCategory,
        deleteAPI: DeleteSetupsSaCouncilCategory,
        hasParent: true,
        parentAPI: GetAllSetupsSaCouncils,
        parentByIdAPI: getSetupsSaCouncilById,
        parentTitle: 'sa-council',
        parentKey: 'sa_councils_uuid',
        titleKey: 'name',
        importEnumItem: LookupsImportEnum.sa_councils_category,
      },
    },
  },
  // {
  //   label: 'banks',
  //   component: LookupsComponent,
  //   props: {
  //     lookup: {
  //       key: 6,
  //       label: 'banks',
  //       valueSingle: 'bank',
  //       feature_name: TablesNameEnum.Banks.key,
  //       updateAPI: UpdateSetupsBank,
  //       createAPI: CreateSetupsBanks,
  //       viewAPI: getSetupsBankById,
  //       listAPI: GetAllSetupsBanks,
  //       deleteAPI: DeleteSetupsBank,
  //     },
  //   },
  // },
];
