import {
  GetAllSetupsBenefitGroup,
  GetSetupsBenefitGroupById,
  CreateSetupsBenefitGroup,
  UpdateSetupsBenefitGroup,
  DeleteSetupsBenefitGroup,
  GetAllSetupsContractMaritalStatus,
  GetSetupsContractMaritalStatusById,
  CreateSetupsContractMaritalStatus,
  UpdateSetupsContractMaritalStatus,
  DeleteSetupsContractMaritalStatus,
  GetAllSetupsTicketRoute,
  GetSetupsTicketRouteById,
  CreateSetupsTicketRoute,
  UpdateSetupsTicketRoute,
  DeleteSetupsTicketRoute,
  GetAllSetupsTransportationType,
  GetSetupsTransportationTypeById,
  CreateSetupsTransportationType,
  UpdateSetupsTransportationType,
  DeleteSetupsTransportationType,
  GetAllSetupsTransportationAllowance,
  GetSetupsTransportationAllowanceById,
  CreateSetupsTransportationAllowance,
  UpdateSetupsTransportationAllowance,
  DeleteSetupsTransportationAllowance,
  GetAllSetupsProjectAllowance,
  GetSetupsProjectAllowanceById,
  CreateSetupsProjectAllowance,
  UpdateSetupsProjectAllowance,
  DeleteSetupsProjectAllowance,
  GetAllSetupsTicketEntitlement,
  GetSetupsTicketEntitlementById,
  CreateSetupsTicketEntitlement,
  UpdateSetupsTicketEntitlement,
  DeleteSetupsTicketEntitlement,
  GetAllSetupsHousingType,
  GetSetupsHousingTypeById,
  CreateSetupsHousingType,
  UpdateSetupsHousingType,
  DeleteSetupsHousingType,
  UpdateSetupsSalaryBasic,
  CreateSetupsSalaryBasic,
  GetSetupsSalaryBasicById,
  GetAllSetupsSalaryBasic,
  DeleteSetupsSalaryBasic,
  UpdateSetupsOverTime,
  CreateSetupsOverTime,
  GetSetupsOverTimeById,
  GetAllSetupsOverTime,
  DeleteSetupsOverTime,
  UpdateSetupsSubCategory,
  CreateSetupsSubCategory,
  GetSetupsSubCategoryById,
  GetAllSetupsSubCategory,
  DeleteSetupsSubCategory,
  UpdateSetupsCriticalCare,
  CreateSetupsCriticalCare,
  GetSetupsCriticalCareById,
  GetAllSetupsCriticalCare,
  DeleteSetupsCriticalCare,
  UpdateSetupsSpecialArea,
  CreateSetupsSpecialArea,
  GetSetupsSpecialAreaById,
  GetAllSetupsSpecialArea,
  DeleteSetupsSpecialArea,
  UpdateSetupsWorkAssignmentForm,
  CreateSetupsWorkAssignmentForm,
  GetSetupsWorkAssignmentFormById,
  GetAllSetupsWorkAssignmentForm,
  DeleteSetupsWorkAssignmentForm,
  UpdateSetupsRecruitmentSource,
  CreateSetupsRecruitmentSource,
  GetSetupsRecruitmentSourceById,
  GetAllSetupsRecruitmentSource,
  DeleteSetupsRecruitmentSource,
} from '../../../../services';
import { LookupsImportEnum, TablesNameEnum } from '../../../../enums';

import LookupsComponent from '../components/lookups/Lookups.Component';

export const OfferClassificationsTabs = [
  {
    label: 'benefit-group',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 1,
        label: 'benefit-group',
        valueSingle: 'benefit-group',
        feature_name: TablesNameEnum.BenefitGroup.key,
        updateAPI: UpdateSetupsBenefitGroup,
        createAPI: CreateSetupsBenefitGroup,
        viewAPI: GetSetupsBenefitGroupById,
        listAPI: GetAllSetupsBenefitGroup,
        deleteAPI: DeleteSetupsBenefitGroup,
        importEnumItem: LookupsImportEnum.benefit_group,
      },
    },
  },
  {
    label: 'contract-marital-status',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 2,
        label: 'contract-marital-status',
        valueSingle: 'contract-marital-status',
        feature_name: TablesNameEnum.ContractMaritalStatus.key,
        updateAPI: UpdateSetupsContractMaritalStatus,
        createAPI: CreateSetupsContractMaritalStatus,
        viewAPI: GetSetupsContractMaritalStatusById,
        listAPI: GetAllSetupsContractMaritalStatus,
        deleteAPI: DeleteSetupsContractMaritalStatus,
        importEnumItem: LookupsImportEnum.contract_marital_status,
      },
    },
  },
  {
    label: 'ticket-route',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 3,
        label: 'ticket-route',
        valueSingle: 'ticket-route',
        feature_name: TablesNameEnum.TicketRoute.key,
        updateAPI: UpdateSetupsTicketRoute,
        createAPI: CreateSetupsTicketRoute,
        viewAPI: GetSetupsTicketRouteById,
        listAPI: GetAllSetupsTicketRoute,
        deleteAPI: DeleteSetupsTicketRoute,
        importEnumItem: LookupsImportEnum.ticket_route,
      },
    },
  },
  {
    label: 'transportation-type',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 4,
        label: 'transportation-type',
        valueSingle: 'transportation-type',
        feature_name: TablesNameEnum.TransportationType.key,
        updateAPI: UpdateSetupsTransportationType,
        createAPI: CreateSetupsTransportationType,
        viewAPI: GetSetupsTransportationTypeById,
        listAPI: GetAllSetupsTransportationType,
        deleteAPI: DeleteSetupsTransportationType,
        importEnumItem: LookupsImportEnum.transportation_type,
      },
    },
  },
  {
    label: 'transportation-allowance',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 5,
        label: 'transportation-allowance',
        valueSingle: 'transportation-allowance',
        feature_name: TablesNameEnum.TransportationAllowance.key,
        updateAPI: UpdateSetupsTransportationAllowance,
        createAPI: CreateSetupsTransportationAllowance,
        viewAPI: GetSetupsTransportationAllowanceById,
        listAPI: GetAllSetupsTransportationAllowance,
        deleteAPI: DeleteSetupsTransportationAllowance,
        importEnumItem: LookupsImportEnum.transportation_allowance,
      },
    },
  },
  {
    label: 'project-allowance',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 6,
        label: 'project-allowance',
        valueSingle: 'project-allowance',
        feature_name: TablesNameEnum.ProjectAllowance.key,
        updateAPI: UpdateSetupsProjectAllowance,
        createAPI: CreateSetupsProjectAllowance,
        viewAPI: GetSetupsProjectAllowanceById,
        listAPI: GetAllSetupsProjectAllowance,
        deleteAPI: DeleteSetupsProjectAllowance,
        importEnumItem: LookupsImportEnum.project_allowance,
      },
    },
  },
  {
    label: 'ticket-entitlement',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 7,
        label: 'ticket-entitlement',
        valueSingle: 'ticket-entitlement',
        feature_name: TablesNameEnum.TicketEntitlement.key,
        updateAPI: UpdateSetupsTicketEntitlement,
        createAPI: CreateSetupsTicketEntitlement,
        viewAPI: GetSetupsTicketEntitlementById,
        listAPI: GetAllSetupsTicketEntitlement,
        deleteAPI: DeleteSetupsTicketEntitlement,
        importEnumItem: LookupsImportEnum.ticket_entitlement,
      },
    },
  },
  {
    label: 'housing-type',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 8,
        label: 'housing-type',
        valueSingle: 'housing-type',
        feature_name: TablesNameEnum.HousingType.key,
        updateAPI: UpdateSetupsHousingType,
        createAPI: CreateSetupsHousingType,
        viewAPI: GetSetupsHousingTypeById,
        listAPI: GetAllSetupsHousingType,
        deleteAPI: DeleteSetupsHousingType,
        importEnumItem: LookupsImportEnum.housing_type,
      },
    },
  },
  {
    label: 'over-time',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 9,
        label: 'over-time',
        valueSingle: 'over-time',
        feature_name: TablesNameEnum.OverTime.key,
        updateAPI: UpdateSetupsOverTime,
        createAPI: CreateSetupsOverTime,
        viewAPI: GetSetupsOverTimeById,
        listAPI: GetAllSetupsOverTime,
        deleteAPI: DeleteSetupsOverTime,
        importEnumItem: LookupsImportEnum.over_time,
      },
    },
  },
  {
    label: 'sub-categories',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 10,
        label: 'sub-categories',
        valueSingle: 'sub-category',
        feature_name: TablesNameEnum.SubCategory.key,
        updateAPI: UpdateSetupsSubCategory,
        createAPI: CreateSetupsSubCategory,
        viewAPI: GetSetupsSubCategoryById,
        listAPI: GetAllSetupsSubCategory,
        deleteAPI: DeleteSetupsSubCategory,
        importEnumItem: LookupsImportEnum.sub_category,
      },
    },
  },
  {
    label: 'salary-basics',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 11,
        label: 'salary-basics',
        valueSingle: 'salary-basic',
        feature_name: TablesNameEnum.SalaryBasic.key,
        updateAPI: UpdateSetupsSalaryBasic,
        createAPI: CreateSetupsSalaryBasic,
        viewAPI: GetSetupsSalaryBasicById,
        listAPI: GetAllSetupsSalaryBasic,
        deleteAPI: DeleteSetupsSalaryBasic,
        importEnumItem: LookupsImportEnum.salary_basic,
      },
    },
  },
  {
    label: 'special-area',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 12,
        label: 'special-areas',
        valueSingle: 'special-area',
        feature_name: TablesNameEnum.SpecialArea.key,
        updateAPI: UpdateSetupsSpecialArea,
        createAPI: CreateSetupsSpecialArea,
        viewAPI: GetSetupsSpecialAreaById,
        listAPI: GetAllSetupsSpecialArea,
        deleteAPI: DeleteSetupsSpecialArea,
        importEnumItem: LookupsImportEnum.special_area,
      },
    },
  },
  {
    label: 'critical-cares',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 13,
        label: 'critical-cares',
        valueSingle: 'critical-care',
        feature_name: TablesNameEnum.CriticalCare.key,
        updateAPI: UpdateSetupsCriticalCare,
        createAPI: CreateSetupsCriticalCare,
        viewAPI: GetSetupsCriticalCareById,
        listAPI: GetAllSetupsCriticalCare,
        deleteAPI: DeleteSetupsCriticalCare,
        importEnumItem: LookupsImportEnum.critical_care,
      },
    },
  },
  {
    label: 'work-assignment-forms',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 12,
        label: 'work-assignment-forms',
        valueSingle: 'work-assignment-form',
        feature_name: TablesNameEnum.WorkAssignmentForm.key,
        updateAPI: UpdateSetupsWorkAssignmentForm,
        createAPI: CreateSetupsWorkAssignmentForm,
        viewAPI: GetSetupsWorkAssignmentFormById,
        listAPI: GetAllSetupsWorkAssignmentForm,
        deleteAPI: DeleteSetupsWorkAssignmentForm,
        importEnumItem: LookupsImportEnum.work_assignment,
      },
    },
  },
  {
    label: 'recruitment-sources',
    component: LookupsComponent,
    props: {
      withDescription: true,
      lookup: {
        key: 13,
        label: 'recruitment-sources',
        valueSingle: 'recruitment-source',
        feature_name: TablesNameEnum.RecruitmentSource.key,
        updateAPI: UpdateSetupsRecruitmentSource,
        createAPI: CreateSetupsRecruitmentSource,
        viewAPI: GetSetupsRecruitmentSourceById,
        listAPI: GetAllSetupsRecruitmentSource,
        deleteAPI: DeleteSetupsRecruitmentSource,
        importEnumItem: LookupsImportEnum.recruitment_source,
      },
    },
  },
  // {
  //   label: 'xs',
  //   component: LookupsComponent,
  //   props: {
  //     withDescription: true,
  //     lookup: {
  //       key: 14,
  //       label: 'xs',
  //       valueSingle: 'x',
  //       feature_name: TablesNameEnum.X.key,
  //       updateAPI: UpdateSetupsX,
  //       createAPI: CreateSetupsX,
  //       viewAPI: GetSetupsXById,
  //       listAPI: GetAllSetupsX,
  //       deleteAPI: DeleteSetupsX,
  //     },
  //   },
  // },
];
