const URL_GET = `${process.env.REACT_APP_DOMIN_PHP_API_GET}/${process.env.REACT_APP_ENDPOINT_API}/ats/${process.env.REACT_APP_VERSION_API}`;
const URL_WRITE = `${process.env.REACT_APP_DOMIN_PHP_API}/${process.env.REACT_APP_ENDPOINT_API}/ats/${process.env.REACT_APP_VERSION_API}`;

// JobBoard
export default {
  ARCHIVED: `${URL_GET}/job/archived`,
  ARCHIVE: `${URL_WRITE}/job/archive`,
  // ACTIVE: `${URL}/job/active`,
  // JOB_SEARCH: `${URL}/job/search`,
  // ACTIVATE: `${URL}/job/activate`,
  // NOTES: `${URL}/notes`,
  // NOTES_MEMBERS: `${URL}/notes/members`,
  // JOB: `${URL}/job`,
  // TEAMS: `${TEAM_URL}/recruiter`,
  // INVITE_TEAM: `${URL}/recruiter/invite`,
  // GET_INVITED_TEAM: `${URL}/recruiter`,
  // TEAM_SEARCH: `${TEAM_URL}/team/search`,
  // TEMPLATES: `${URL}/template`,
  // PIPELINE: `${URL}/job/pipeline`,
  // PIPELINE_STAGE: `${URL}/job/pipeline/stage`,
  // JOB_STAGES: `${URL}/stage/list`,
  // TIME_LIMITS: `${URL}/job/time_limits`,
  // NUMBER_OF_RETAKE: `${URL}/job/number_of_retake`,
  // GET_CANDIDATES: `${URL}/job/candidates`,
  // FIND_CANDIDATE: `${URL}/job/video`,
  // DISCUSSION: `${URL}/discussion`,
  // COMMENTS: `${URL}/comments`,
  // COMMENTS_REPLY: `${URL}/comments/reply`,
  SEND_QUESTIONNAIRE: `${URL_WRITE}/candidate/send-questionnaire`,
  VIEW_QUESTIONNAIRE: `${URL_GET}/job/questionnaire/view`,
  // RECENT_UPLOADS: `${URL}/job/rms`,
  RMS_JOBS_LIST: `${URL_GET}/job/list`,
  // CANDIDATE_EVALUATION: `${URL}/job/evaluation`,

  // Responsibility: `${USER_URL}/responsibility`,
  // SUB_USERS: `${USER_URL}/users`,
  // ASSESSMENT_RATE: `${CANDIDATE_URL}/assessment/rate`,
  // NOTES_LIST: `${URL}/notes/list`,
  // INVITE_CANDIDATE: `${URL}/assessment/invite/candidate`,
  // GET_INVITED_CANDIDATES: `${URL}/assessment/invited`,
  // getDiscussionReplies: `${URL}/discussion/reply`,
  // Rating: `${URL}/rates`,
  // PIPELINE: `${URL}/assessment/pipeline`,
  // PIPELINE_STAGE: `${URL}/assessment/pipeline/stage`,
  // PIPELINE_ADD_STAGE: `${URL}/stage`,
  // MOVE_STAGE: `${URL}/candidate/move-stage`,
  // STAGE_ORDER: `${URL}/stage/reorder`,
  // InvitedMembers: `${URL}/assessment/invited`,
  // InvitedRecruiters: `${URL}/assessment/recruiter`,
  // InviteRecruiters: `${URL}/assessment/recruiter/invite`,
  // LOGS: `${URL}/assessment/recruiter/log`,
  // CANDIDATE_SEARCH: `${COMPANY_URL}/candidate/search`,
};
