import { lazy } from 'react';
const ImportsManagementPage = lazy(() =>
  import(
    '../../../pages/setups/imports-setups/imports-management/ImportsManagement.Page'
  ),
);

export const ImportsSetupsRoute = [
  {
    path: '/personal-classification',
    name: 'personal-classification',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: true,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: WorkflowsPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/education-classification',
    name: 'education-classification',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: true,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: WorkflowsPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/work-classification',
    name: 'work-classification',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: false,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: CommitteesPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/offer-classification',
    name: 'offer-classification',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: false,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: CommitteesPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/file-classification',
    name: 'file-classification',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: false,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: CommitteesPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/organization-setup',
    name: 'organization-setup',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: false,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: CommitteesPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
  {
    path: '/administration-setup',
    name: 'administration-setup',
    component: ImportsManagementPage,
    layout: '/setups/imports',
    default: false,
    authorize: false,
    isRecursive: false,
    // defaultPermissions: CommitteesPermissions,
    isRoute: true,
    isExact: true,
    children: [],
  },
];
