/* exampleCreateVideoAssessmentRequest */
export const ExampleCreateVideoAssessmentRequest = {
  language_id: 'db06ff1e-357f-4e1a-aa86-40173b494baf',
  title: 'Private Assessment',
  type: 1,
  questions: [
    {
      title:
        'Tell me about yourself, your educational background & your Experience.?',
      time_limit: 120,
      model_answer: null,
      number_of_retake: 2,
      expected_keyword: [
        'one',
        'two',
        'three',
        'four',
        'leader',
        'motivation',
        'finance',
        'accountant',
        'united kingdom',
        'coventry',
        'manchester',
        'Jordan university',
      ],
    },
    {
      title: 'Describe your perfect work environment.?',
      time_limit: 120,
      model_answer: null,
      number_of_retake: 2,
      expected_keyword: [
        'team work',
        'passion',
        'dynamic',
        'professional',
        'friendly',
        'perfect',
        'work',
        'environment',
      ],
    },
    {
      title: 'What are your top 3 strengths?',
      time_limit: 120,
      model_answer: null,
      number_of_retake: 2,
      expected_keyword: [
        'top',
        'strength',
        'first',
        'second',
        'time management',
        'creativity',
        'focused',
        'flexibilty',
      ],
    },
  ],
  user_invited: [
    {
      first_name: 'Suha',
      last_name: 'Hijawi',
      email: 'msalahat88@gmail.com',
      phone: '0798981496',
    },
  ],
  email_subject: '{company_name} -  {candidate_name}',
  email_body:
    "<div class='container' style='line-height: 35.4px;font-family:Ubuntu,Arial,Sans Serif,Ubuntu;width: 50%;margin-left: auto;margin-right: auto;font-size: 16px'><div class='logo' style='width: 100%;background-color: #bababa'>{company_logo}</div><div class='container' style='border: 1px solid #e2e2e2; padding: 20px;border-top: 0px;'><p>Dear {candidate_name},</p><p>Thank you for your interest in our <b>{job_title}</b> position.</p><p> The next step in our hiring process is a virtual one-way video interview.</p><p>We’d like to invite you to this interview to enable us to get to know you better.</p><p>Interview deadline : {video_assessment_deadline}</p><p>Click on the button below to start your assessment.</p><p>{video_assessment_invite_link}</p><p>Good luck!</p><p>{recruiter_name} / {company_name} Recruitment Team</p></div><p style='font-size: 11px;line-height: 13px'>NOTICE TO RECIPIENT | The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.</p></div>",
  deadline: '2021-09-19',
  video_uuid: null,
  media_uuid: null,
  pipeline_uuid: '7dbe8d9c-8c27-4a82-9fba-155e5832a087',
  teams_invited: [],
  is_public: false,
  category_uuid: '6b0fed13-7b73-475f-b0a9-0cedb3cee6cb',
};
